### ISSUE TITLE
Illegal instance creation problems

### ISSUE THREAD

**Issue by Kampfkarren** [LPGhatguy/lemur#13]
Right now, you can use `Instance.new("TestService")` (or any other illegal class) when you usually can't on Roblox. You shouldn't have to use `game:GetService` for all of these as that'll end up making tests more difficult.

Instance.new should work like it does on Roblox for the project's sake. At the same time, there should be an internal function like `Instance.newForced` or something along those lines that'll bypass those checks entirely.

**Comment by LPGhatguy** [comment]
This is actually pretty straightforward to fix now, we just stop putting those instances into `init`! Since you can directly import instance files and use the `new` method, you can bypass `Instance.new` in internal code.

It's possible that we should rename that file and name it something like `creatableInstances`, or keep it where it is right now and have it check for a `creatable` flag on each instance to decide whether to allow it.
