### ISSUE TITLE
Why does :Wait() execute :Fire()?

### ISSUE THREAD

**Issue by Kampfkarren** [LPGhatguy/lemur#3]
https://github.com/LPGhatguy/lemur/blob/705238b707d48ee8ce926814aa0cf22393caa32e/lib/Signal.lua#L67-L70

I know this is placeholder while there isn't a thread scheduler, but why this behavior? Why not an error?

**Comment by LPGhatguy** [comment]
Ah darn, I guess I forgot to document that behavior correctly.

It was originally implemented like that due to an earlier version of [Rodux](https://github.com/Roblox/Rodux) and its events, but that code has since changed. It's probably safe to remove `Wait()` from the signal implementation until #1 is solved!

**Comment by LPGhatguy** [comment]
Okay, I got that nipped in the bud, thank you!
